before_script:
  - export https_proxy=http://m100.cache.pvt:3128
  - export http_proxy=http://m100.cache.pvt:3128
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --prefer-install=auto --no-interaction

test:7.1:
  image: akeb/php-fpm:7.1
  tags:
    - mrgs
  script:
    - XDEBUG_MODE=coverage php7.1 vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.1.xml


test:7.2:
  image: akeb/php-fpm:7.2
  tags:
    - mrgs
  script:
    - XDEBUG_MODE=coverage php7.2 vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.2.xml

test:7.3:
  image: akeb/php-fpm:7.3
  tags:
    - mrgs
  script:
    - XDEBUG_MODE=coverage php7.3 vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.3.xml
