before_script:
  - bash ci/docker_install.sh > /dev/null
  - curl -s http://getcomposer.org/installer | php
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - php composer.phar install --prefer-source --no-interaction
  - phpenv rehash


test:7.0:
  image: php:7.0
  tags:
    - myua
  script:
    - php vendor/bin/phpunit -c phpunit.xml

test:7.1:
  image: php:7.1
  tags:
    - myua
  script:
    - php vendor/bin/phpunit -c phpunit.xml

test:7.2:
  image: php:7.2
  tags:
    - myua
  script:
    - php vendor/bin/phpunit -c phpunit.xml

test:7.3:
  image: php:7.3
  tags:
    - myua
  script:
    - php vendor/bin/phpunit -c phpunit.xml

test:7.4:
  image: php:7.4
  tags:
    - myua
  script:
    - php vendor/bin/phpunit -c phpunit.xml

test:8.0:
  image: php:8.0
  tags:
    - myua
  script:
    - php vendor/bin/phpunit -c phpunit.xml