language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - curl -s http://getcomposer.org/installer | php
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - php composer.phar install --prefer-source --no-interaction
  - phpenv rehash

script:
  - php -n -dzend_extension=xdebug -dxdebug.mode=coverage vendor/bin/phpunit -d xdebug.coverage_enable=1 -c phpunit.xml

