name: PHP TEST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test_7_1:
    runs-on: ubuntu-latest
    container: akeb/php-fpm:7.1
    steps:
      - uses: actions/checkout@v3
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: XDEBUG_MODE=coverage php7.1 vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.1.xml
  test_7_2:
    runs-on: ubuntu-latest
    container: akeb/php-fpm:7.2
    steps:
      - uses: actions/checkout@v3
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: XDEBUG_MODE=coverage php7.2 vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.2.xml
  test_7_3:
    runs-on: ubuntu-latest
    container: akeb/php-fpm:7.3
    steps:
      - uses: actions/checkout@v3
      - name: Cleanup
        run: rm -rf vendor composer.lock
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: XDEBUG_MODE=coverage php7.3 vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.3.xml
